# -*- coding: utf-8 -*-
import json

from odoo import api, fields, models


class EventEvent(models.Model):
    _inherit = "event.event"

    gl_event_header_image = fields.Image(
        string="Website-/Übersichtsbild",
        max_width=1920,
        max_height=1080,
        help=(
            "Optionales Bildfeld für das Website-Cover. "
            "Wenn ein vorhandenes Studio-Bildfeld erkannt wird, wird dieses bevorzugt."
        ),
    )

    def _gl_candidate_cover_image_fields(self):
        """Return image/binary fields that may be used as source for the website cover.

        Reihenfolge ist bewusst wichtig:
        1. bekannte Groundlift/Odoo-Studio-Felder
        2. generische Studio-Namen
        3. das durch dieses Modul bereitgestellte Feld
        4. ein eventuell vorhandenes Standard-Bildfeld
        """
        return [
            "x_studio_x_studio_binary_field_4ut_1jl7us7lt",
            "x_studio_event_header_image",
            "x_studio_website_header",
            "x_studio_event_header",
            "x_studio_header_image",
            "x_studio_website_header_image",
            "x_studio_website_cover_image",
            "gl_event_header_image",
            "image_1920",
        ]

    def _gl_existing_cover_image_fields(self):
        """Return candidate fields that actually exist on this database."""
        existing = []
        for field_name in self._gl_candidate_cover_image_fields():
            field = self._fields.get(field_name)
            if field and field.type == "binary":
                existing.append(field_name)
        return existing

    def _gl_get_cover_source_field(self):
        """Return the first available non-empty binary/image field for this event."""
        self.ensure_one()
        for field_name in self._gl_existing_cover_image_fields():
            if self[field_name]:
                return field_name
        return False

    def _gl_get_default_cover_properties_json(self):
        """Return Odoo's default event cover properties as JSON."""
        props = self._default_cover_properties()
        return json.dumps(props)

    def _gl_build_cover_properties_json(self, source_field):
        """Build cover_properties JSON pointing to the selected event image field."""
        self.ensure_one()
        try:
            props = json.loads(self.cover_properties or "{}")
        except Exception:
            props = {}

        props.setdefault("opacity", "0.4")
        props.setdefault("resize_class", "cover_auto")

        unique_value = ""
        if self.write_date:
            unique_value = fields.Datetime.to_string(self.write_date).replace(" ", "-").replace(":", "")

        image_url = f"/web/image/event.event/{self.id}/{source_field}"
        if unique_value:
            image_url = f"{image_url}?unique={unique_value}"

        props["background-image"] = f"url('{image_url}')"
        return json.dumps(props)

    def _gl_current_cover_points_to_event_image(self):
        """Check whether current cover was generated by this sync logic."""
        self.ensure_one()
        marker = f"/web/image/event.event/{self.id}/"
        return bool(self.cover_properties and marker in self.cover_properties)

    def _gl_sync_event_cover_from_image(self):
        """Synchronize website cover_properties from the selected image field.

        If no source image exists and the current cover was generated by this module,
        the cover falls back to Odoo's standard event cover.
        """
        for event in self.sudo():
            if not event.id:
                continue

            source_field = event._gl_get_cover_source_field()
            if source_field:
                cover_json = event._gl_build_cover_properties_json(source_field)
            elif event._gl_current_cover_points_to_event_image():
                cover_json = event._gl_get_default_cover_properties_json()
            else:
                continue

            if event.cover_properties != cover_json:
                event.with_context(gl_skip_event_cover_sync=True).write({"cover_properties": cover_json})

    @api.model_create_multi
    def create(self, vals_list):
        events = super().create(vals_list)
        if not self.env.context.get("gl_skip_event_cover_sync"):
            events._gl_sync_event_cover_from_image()
        return events

    def write(self, vals):
        res = super().write(vals)
        if self.env.context.get("gl_skip_event_cover_sync"):
            return res

        image_fields = set(self._gl_existing_cover_image_fields())
        if image_fields.intersection(vals.keys()):
            self._gl_sync_event_cover_from_image()
        return res
