# -*- coding: utf-8 -*-
from hmac import compare_digest
from datetime import timedelta
from markupsafe import Markup, escape
from odoo import fields
from odoo.tools import html2plaintext

from odoo import http
from odoo.exceptions import ValidationError
from odoo.http import request
from odoo.tools.misc import formatLang


class EventArtistPortalController(http.Controller):

    def _get_event_by_token(self, event_id, token, require_active=False):
        event = request.env['event.event'].sudo().browse(event_id).exists()
        if not event or not event.artist_portal_access_token:
            return request.env['event.event'].sudo()
        if not compare_digest(str(event.artist_portal_access_token), str(token or '')):
            return request.env['event.event'].sudo()
        if require_active and not event._is_artist_portal_stage():
            return request.env['event.event'].sudo()
        return event

    def _get_portal_line(self, event, line_id, require_active=True):
        """Return only an entry created through this exact event portal.

        The event token authorizes access to the event, but the line id itself is
        never trusted. This prevents modifying a guest-list entry from another
        event by changing the id in the request.
        """
        try:
            line_id = int(line_id)
        except (TypeError, ValueError):
            return request.env['gl.event.guestlist.line'].sudo()

        domain = [
            ('id', '=', line_id),
            ('event_id', '=', event.id),
            ('artist_portal_created', '=', True),
        ]
        if require_active:
            domain.append(('active', '=', True))
        return request.env['gl.event.guestlist.line'].sudo().search(domain, limit=1)

    def _ticket_price_label(self, ticket):
        """Return the ticket price with the currency's normal precision.

        Do not use the guestlist price-option name here: that name is generated by
        the base guestlist module and may contain the raw Python float.
        """
        if 'price' not in ticket._fields:
            return ''
        currency = ticket.currency_id if 'currency_id' in ticket._fields else ticket.event_id.company_id.currency_id
        return formatLang(request.env, ticket.price or 0.0, currency_obj=currency)

    def _ticket_option_label(self, option):
        """Build a clean, currency-formatted label for a guestlist ticket option."""
        ticket = option.ticket_id
        if not ticket:
            return option.name or ''

        parts = []
        if ticket.name:
            parts.append(ticket.name)
        product = getattr(ticket, 'product_id', False)
        if product and product.display_name and product.display_name not in parts:
            parts.append(product.display_name)

        price_label = self._ticket_price_label(ticket)
        if price_label:
            parts.append(price_label)
        return ' – '.join(parts) or option.name or 'Ticket'

    def _entry_form_from_post(self, post):
        return {
            'entry_type': (post.get('entry_type') or '').strip(),
            'name': (post.get('name') or '').strip(),
            'quantity': (post.get('quantity') or '1').strip(),
            'price_option_id': (post.get('price_option_id') or '').strip(),
            'contact_data': (post.get('contact_data') or '').strip(),
            'submitted_by': (post.get('submitted_by') or '').strip(),
            'note': (post.get('note') or '').strip(),
        }

    def _validate_entry_form(self, event, form):
        """Validate a portal entry and resolve its guest-list price option."""
        if form['entry_type'] not in ('guestlist', 'box_office'):
            raise ValidationError('Bitte wähle Gästeliste oder Abendkasse aus.')
        if not form['name']:
            raise ValidationError('Bitte gib den Namen des Gastes an.')
        if len(form['name']) > 160:
            raise ValidationError('Der Gastname ist zu lang.')
        if len(form['contact_data']) > 250:
            raise ValidationError('Die Kontaktdaten sind zu lang.')
        if len(form['submitted_by']) > 160:
            raise ValidationError('Der Ansprechpartner ist zu lang.')
        if len(form['note']) > 1500:
            raise ValidationError('Die Bemerkung ist zu lang.')

        try:
            quantity = int(form['quantity'])
        except (TypeError, ValueError):
            quantity = 0
        if quantity < 1 or quantity > 20:
            raise ValidationError('Die Anzahl muss zwischen 1 und 20 liegen.')

        event._sync_guestlist_price_options()
        if form['entry_type'] == 'guestlist':
            option = event.guestlist_price_option_ids.filtered(
                lambda opt: opt.active and opt.is_free
            )[:1]
            if not option:
                raise ValidationError('Die kostenlose Gästelisten-Kategorie konnte nicht gefunden werden.')
        else:
            try:
                option_id = int(form['price_option_id'])
            except (TypeError, ValueError):
                option_id = 0
            option = request.env['gl.event.guestlist.price.option'].sudo().search([
                ('id', '=', option_id),
                ('event_id', '=', event.id),
                ('active', '=', True),
                ('is_free', '=', False),
                ('is_waitlist', '=', False),
                ('ticket_id', '!=', False),
            ], limit=1)
            if not option or option.ticket_id.gl_is_guestlist_summary_ticket:
                raise ValidationError('Bitte wähle eine gültige Ticketkategorie für die Abendkasse aus.')

        return quantity, option

    def _entry_write_values(self, form, quantity, option):
        return {
            'name': form['name'],
            'quantity': str(quantity),
            'price_option_id': option.id,
            'ordered_by': 'personal',
            'contact_data': form['contact_data'] or False,
            'note': form['note'] or False,
            'employee_id': False,
            'artist_portal_entry_type': form['entry_type'],
            'artist_portal_submitted_by': form['submitted_by'] or False,
        }

    def _prepare_values(
        self, event, token, success=None, error=None, form=None,
        edit_line_id=None, edit_form=None,
    ):
        event = event.sudo()
        accounting = event._is_artist_portal_accounting_stage()
        media_stage = event._is_artist_portal_media_stage()
        video_stage = event._is_artist_portal_video_stage()
        pitch = (request.env['gl.artist.portal.video.config'].sudo().get_portal_pitch()
                 if video_stage else {'headline': '', 'eyebrow': ''})
        media_values = {
            'event': event,
            'token': token,
            'portal_active': accounting or video_stage or media_stage or event._is_artist_portal_stage(),
            'extended_portal': bool(event.artist_portal_extended_enabled),
            'accounting_active': accounting,
            'gema_url': event._artist_portal_valid_gema_url() if accounting else False,
            'setlist_submitted': bool(event.artist_portal_setlist_submitted),
            'media_active': media_stage,
            'show_photos': media_stage and event._artist_portal_section_enabled('photos'),
            'show_press': media_stage and event._artist_portal_section_enabled('press'),
            'show_tech': media_stage and event._artist_portal_section_enabled('tech'),
            'show_hospitality': media_stage and event._artist_portal_section_enabled('hospitality'),
            'guestlist_active': event._is_artist_portal_stage(),
            'video_active': video_stage,
            'video_pitch_headline': pitch['headline'],
            'video_pitch_eyebrow': pitch['eyebrow'],
            'videos': (request.env['gl.artist.portal.video.config'].sudo().get_portal_videos()
                       if video_stage else []),
            'press_short_value': html2plaintext(event['x_studio_event_kurzbeschreibung'] or '') if 'x_studio_event_kurzbeschreibung' in event._fields else '',
            'press_long_value': event.artist_portal_press_long or '',
            'press_short_field': 'x_studio_event_kurzbeschreibung' in event._fields,
            'rider_tech_available': 'x_studio_tech_rider' in event._fields,
            'rider_hospitality_available': 'x_studio_hospitality_rider' in event._fields,
            'photo_editable': event._artist_portal_photos_editable(),
            'media_notice': request.params.get('media'),
            'success': success,
            'error': error,
            'contact_draft': '',
        }
        # In Gebucht there is no guest-list UI; avoid creating ticket/guest-list
        # price options just because an artist opens the media upload portal.
        if not media_values['guestlist_active']:
            return media_values
        event._sync_guestlist_price_options()

        real_tickets = event.event_ticket_ids.filtered(
            lambda ticket: not ticket.gl_is_guestlist_summary_ticket
        ).sorted(lambda ticket: (ticket.sequence, ticket.id))

        active_lines = event.guestlist_line_ids.sudo().filtered(
            lambda line: line.active and not line.is_waitlist
        )
        portal_lines = event.guestlist_line_ids.sudo().filtered(
            lambda line: line.active and line.artist_portal_created
        ).sorted(lambda line: line.id, reverse=True)

        global_remaining = event._get_remaining_seats_after_guestlist()
        ticket_rows = []
        total_sold = 0
        total_portal_box_office = 0
        total_portal_guestlist = 0

        for line in active_lines.filtered('artist_portal_created'):
            if line.artist_portal_entry_type == 'box_office':
                total_portal_box_office += line.quantity_int
            elif line.artist_portal_entry_type == 'guestlist':
                total_portal_guestlist += line.quantity_int

        for ticket in real_tickets:
            sold = ticket.seats_taken or 0
            total_sold += sold
            guestlist_qty = ticket._get_guestlist_counted_qty_for_ticket()
            portal_box_office_qty = sum(
                active_lines.filtered(
                    lambda line: line.artist_portal_created
                    and line.artist_portal_entry_type == 'box_office'
                    and line.price_option_id.ticket_id == ticket
                ).mapped('quantity_int')
            )

            ticket_remaining = None
            if ticket.seats_max:
                ticket_remaining = max((ticket.seats_available or 0) - guestlist_qty, 0)

            if global_remaining is False:
                effective_remaining = ticket_remaining
            elif ticket_remaining is None:
                effective_remaining = max(global_remaining, 0)
            else:
                effective_remaining = max(min(ticket_remaining, global_remaining), 0)

            ticket_rows.append({
                'ticket': ticket,
                'sold': sold,
                'guestlist_qty': guestlist_qty,
                'portal_box_office_qty': portal_box_office_qty,
                'remaining': effective_remaining,
                'price_label': self._ticket_price_label(ticket),
            })

        if global_remaining is False:
            if real_tickets and all(ticket.seats_max for ticket in real_tickets):
                overall_remaining = sum(
                    max((ticket.seats_available or 0) - ticket._get_guestlist_counted_qty_for_ticket(), 0)
                    for ticket in real_tickets
                )
            else:
                overall_remaining = None
        else:
            overall_remaining = max(global_remaining, 0)

        box_office_options = event.guestlist_price_option_ids.filtered(
            lambda option: option.active
            and not option.is_free
            and not option.is_waitlist
            and option.ticket_id
            and not option.ticket_id.gl_is_guestlist_summary_ticket
        ).sorted(lambda option: (option.sequence, option.id))
        box_office_rows = [
            {
                'option': option,
                'label': self._ticket_option_label(option),
            }
            for option in box_office_options
        ]
        option_labels = {
            option.id: self._ticket_option_label(option)
            for option in event.guestlist_price_option_ids.filtered(lambda option: option.ticket_id)
        }

        media_values.update({
            'ticket_rows': ticket_rows,
            'box_office_options': box_office_options,
            'box_office_rows': box_office_rows,
            'option_labels': option_labels,
            'portal_lines': portal_lines,
            'total_sold': total_sold,
            'overall_remaining': overall_remaining,
            'total_portal_guestlist': total_portal_guestlist,
            'total_portal_box_office': total_portal_box_office,
            'form': form or {},
            'edit_line_id': edit_line_id,
            'edit_form': edit_form or {},
            'quantity_values': list(range(1, 21)),
        })

        return media_values

    @http.route(
        '/event/artist/<int:event_id>/<string:token>',
        type='http', auth='public', website=True, sitemap=False, methods=['GET']
    )
    def artist_portal_page(self, event_id, token, **kwargs):
        event = self._get_event_by_token(event_id, token, require_active=False)
        if not event:
            return request.not_found()
        success = kwargs.get('success')
        if success == '1':
            success = 'added'
        values = self._prepare_values(event, token, success=success)
        return request.render('gl_event_artist_portal.artist_portal_page', values)

    @http.route(
        '/event/artist/<int:event_id>/<string:token>/video-contact',
        type='http', auth='public', website=True, sitemap=False, methods=['POST']
    )
    def artist_portal_video_contact(self, event_id, token, **post):
        # Contact form is available with the videos in Angebot, Gebucht,
        # Angekündigt, but never in Abrechnung / Beendet.
        event = self._get_event_by_token(event_id, token, require_active=False)
        if not event or not event._is_artist_portal_video_stage():
            return request.not_found()
        if post.get('contact_website'):
            # Honeypot for unsophisticated spam bots; no message is created.
            return request.redirect('/event/artist/%s/%s' % (event.id, token), code=303)
        message = (post.get('contact_message') or '').strip()
        if not message or len(message) > 3000:
            values = self._prepare_values(
                event, token, error='Bitte eine Nachricht mit maximal 3.000 Zeichen eingeben.')
            values['contact_draft'] = message[:3000]
            return request.render('gl_event_artist_portal.artist_portal_page', values)
        with request.env.cr.savepoint():
            # Make double clicks/automated requests less prone to duplicate
            # chatter entries and abuse of the publicly accessible token URL.
            request.env.cr.execute('SELECT id FROM event_event WHERE id = %s FOR UPDATE', [event.id])
            event.invalidate_recordset(['artist_portal_contact_last_sent_at'])
            now = fields.Datetime.to_datetime(fields.Datetime.now())
            last = fields.Datetime.to_datetime(event.artist_portal_contact_last_sent_at)
            if last and now - last < timedelta(seconds=30):
                values = self._prepare_values(
                    event, token, error='Bitte vor der nächsten Nachricht kurz warten.')
                values['contact_draft'] = message
                return request.render('gl_event_artist_portal.artist_portal_page', values)
            body = Markup('<p><strong>Nachricht aus dem Künstler-/Agenturportal</strong></p>'
                          '<p>%s</p>') % escape(message).replace('\n', Markup('<br/>'))
            # A normal (non-internal) Chatter comment on THIS event. Do not
            # claim to impersonate a specific contact: the link may be shared.
            event.sudo().with_context(
                mail_create_nosubscribe=True, mail_notify_noemail=True,
                mail_notify_force_send=False,
            ).message_post(
                body=body, subject='Anfrage zur Event-Aufzeichnung',
                message_type='comment', subtype_xmlid='mail.mt_comment',
            )
            event.with_context(artist_portal_source=True).write({
                'artist_portal_contact_last_sent_at': fields.Datetime.now(),
            })
        return request.redirect('/event/artist/%s/%s?success=contact' % (event.id, token), code=303)

    @http.route(
        '/event/artist/<int:event_id>/<string:token>/add',
        type='http', auth='public', website=True, sitemap=False, methods=['POST']
    )
    def artist_portal_add(self, event_id, token, **post):
        event = self._get_event_by_token(event_id, token, require_active=True)
        if not event:
            return request.not_found()

        form = self._entry_form_from_post(post)
        try:
            quantity, option = self._validate_entry_form(event, form)
            vals = self._entry_write_values(form, quantity, option)
            vals.update({
                'event_id': event.id,
                'artist_portal_created': True,
            })
            # The guest-list model performs its capacity validation after create.
            # A savepoint guarantees that a rejected overbooking is fully rolled
            # back even though we render the validation error ourselves.
            with request.env.cr.savepoint():
                request.env['gl.event.guestlist.line'].sudo().create(vals)
        except ValidationError as exc:
            values = self._prepare_values(event, token, error=str(exc), form=form)
            return request.render('gl_event_artist_portal.artist_portal_page', values)

        return request.redirect('/event/artist/%s/%s?success=added' % (event.id, token))

    @http.route(
        '/event/artist/<int:event_id>/<string:token>/update/<int:line_id>',
        type='http', auth='public', website=True, sitemap=False, methods=['POST']
    )
    def artist_portal_update(self, event_id, token, line_id, **post):
        event = self._get_event_by_token(event_id, token, require_active=True)
        if not event:
            return request.not_found()
        line = self._get_portal_line(event, line_id, require_active=True)
        if not line:
            return request.not_found()

        form = self._entry_form_from_post(post)
        try:
            quantity, option = self._validate_entry_form(event, form)
            vals = self._entry_write_values(form, quantity, option)
            # Same protection as on create: if the new quantity/category would
            # exceed capacity, the guest-list constraint raises and the original
            # entry remains untouched.
            with request.env.cr.savepoint():
                line.write(vals)
        except ValidationError as exc:
            values = self._prepare_values(
                event,
                token,
                error=str(exc),
                edit_line_id=line.id,
                edit_form=form,
            )
            return request.render('gl_event_artist_portal.artist_portal_page', values)

        return request.redirect('/event/artist/%s/%s?success=updated' % (event.id, token))

    @http.route(
        '/event/artist/<int:event_id>/<string:token>/cancel/<int:line_id>',
        type='http', auth='public', website=True, sitemap=False, methods=['POST']
    )
    def artist_portal_cancel(self, event_id, token, line_id, **post):
        event = self._get_event_by_token(event_id, token, require_active=True)
        if not event:
            return request.not_found()
        line = self._get_portal_line(event, line_id, require_active=True)
        if not line:
            return request.not_found()

        try:
            # Archive instead of deleting: the capacity is released immediately,
            # while Groundlift keeps an internal audit trail of the cancellation.
            with request.env.cr.savepoint():
                line.write({'active': False})
        except ValidationError as exc:
            values = self._prepare_values(event, token, error=str(exc))
            return request.render('gl_event_artist_portal.artist_portal_page', values)

        return request.redirect('/event/artist/%s/%s?success=cancelled' % (event.id, token))
