# -*- coding: utf-8 -*-
{
    "name": "Inbox Filter",
    "summary": "GPT-gestützte Sortierung neuer CRM-Leads mit getrennter SPAM-/Newsletter-Erkennung, Historie, Re-Learning und Kundendienst-Übergabe.",
    "version": "19.0.1.1.0",
    "category": "Sales/CRM",
    "author": "Groundlift / OpenAI",
    "website": "https://groundlift.de",
    "license": "LGPL-3",
    "depends": [
        "base",
        "web",
        "crm",
        "mail",
        "project",
        "event",
        "hr",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/inbox_filter_prompt_data.xml",
        "data/inbox_filter_settings_data.xml",
        "views/inbox_filter_workspace_views.xml",
        "views/inbox_filter_history_views.xml",
        "views/inbox_filter_settings_views.xml",
        "views/crm_menu_views.xml",
        "wizards/inbox_filter_wizard_views.xml",
    ],
    "installable": True,
    "application": True,
}
