# -*- coding: utf-8 -*-
{
    "name": "GROUNDLIFT Home Assistant Steuerung",
    "summary": "Home-Assistant-Dashboard, Sensorverlauf, Steuerung und Event-/Kino-Automationen",
    "version": "19.0.1.1.1",
    "category": "Operations/IoT",
    "author": "GROUNDLIFT / ChatGPT",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
        "web",
        "event",
        "website",
        "gl_kino_newsletter_nl2go",
    ],
    "data": [
        "security/groups.xml",
        "security/ir.model.access.csv",
        "data/default_data.xml",
        "data/ir_cron.xml",
        "views/ha_config_views.xml",
        "views/ha_entity_views.xml",
        "views/ha_rule_views.xml",
        "views/ha_dashboard_views.xml",
        "views/ha_alert_views.xml",
        "views/ha_schedule_views.xml",
        "views/menu_views.xml",
        "views/dashboard_templates.xml",
    ],
    "assets": {},
    "installable": True,
    "application": True,
}
