{
    "name": "Groundlift Medienfreigabe",
    "summary": "PIN-geschützte Foto-/Video-Freigabe mit Hetzner FTP/SFTP-Speicher",
    "version": "19.0.1.0.9",
    "category": "Website/Website",
    "author": "Groundlift / OpenAI",
    "website": "https://www.groundlift.de",
    "license": "LGPL-3",
    "depends": ["base", "website", "web"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/ir_cron.xml",
        "views/connection_views.xml",
        "views/person_views.xml",
        "views/backend_actions.xml",
        "views/folder_views.xml",
        "views/media_file_views.xml",
        "views/vote_views.xml",
        "wizard/upload_wizard_views.xml",
        "views/menu_views.xml",
        "views/website_templates.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "groundlift_media_approval/static/src/css/media_approval.css",
        ],
    },
    "application": True,
    "installable": True,
}
